spring:
  application:
    name: DreamWeaver
  profiles:
    group:
      local: local-db, local-port, common
      dev : dev-db, dev-port, common
    active: ${ACTIVE_PROFILE}

---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true

---
spring:
  config:
    activate:
      on-profile: local-db
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
openai:
  secret-key: ${OPEN_AI_KEY}
  base-url: https://api.openai.com/v1
  chat:
    model: ${OPEN_AI_TEXT_MODEL}
    max-tokens: ${OPEN_AI_MAX_TOKEN}
    temperature: ${OPEN_AI_TEMPERATURE}
  image:
    model: ${OPEN_AI_IMAGE_MODEL}
    size: 1024x1024
    quality: low

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: dreamweaver-bucket
      base-url: https://dreamweaver-bucket.s3.ap-northeast-2.amazonaws.com


---
spring:
  config:
    activate:
      on-profile: local-port
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: dev-db
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_DATASOURCE_USERNAME}
    password: ${DEV_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: dev-port
server:
  port: 8080